### ISSUE TITLE
pr #31 fails as there is an error in running a job from a qobj

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-jku-provider#32] opened 2019-02-19 02:32 UTC
backend.run(qobj) fails in pr #31

**Comment by gadial** [comment] 2019-02-19 14:57
I am not sure I was able to reproduce. I got failures stemming from the use of temporary files, most of which could be removed because of improvements to the JKU executable. This was addressed in #37. I am closing the issue for now, as I could not get a file on backends.py file after this fix.

**Closed by gadial** 2019-02-19 14:57 UTC
Labels: for first release
